version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: speerDB
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
    ports:
      - "9200:9200"

  speer-application:
    image: speer-application-v2
    depends_on:
      - elasticsearch
      - mysql
    ports:
      - "8080:8080"